### ISSUE TITLE
RequestError does not provide a way for access the error message

### ISSUE THREAD

**Issue by YuriHeupa** [cesarferreira/AndroidQuickUtils#2]
https://github.com/cesarferreira/AndroidQuickUtils/blob/master/library/src/main/java/quickutils/core/rest/RequestError.java

The RequestError constructor initializes the errorMessage field, but the class does not have a public method for accessing this value, making impossible to the rest api access the result of the request

I will make a pull request for it

`UPDATE` https://github.com/cesarferreira/AndroidQuickUtils/pull/3

**Comment by cesarferreira** [comment]
Since your pull request (#3)[https://github.com/cesarferreira/AndroidQuickUtils/pull/3] fixes this I'll close this issue, thanks
