### ISSUE TITLE
ATTENTION: com.android.volley.TimeoutError

### ISSUE THREAD

**Issue by diogo10** [cesarferreira/AndroidQuickUtils#5]
Hii...I am getting this error...sometimes works and sometimes no....my request haven't nothing special....how can I set a timeout?

ATTENTION: com.android.volley.TimeoutError

**Comment by MTersigni** [comment]
I have the same problem.
Have you found a solution?

**Comment by diogo10** [comment]
Hi @MTersigni , 

I am not sure which way I took to fix it (long time ago haha), but I would say....I may change the library. I just don't like volley at all lol
