### ISSUE TITLE
Incompatible with parse.com

### ISSUE THREAD

**Issue by diogo10** [cesarferreira/AndroidQuickUtils#6]
Both use OkHttp

**Comment by cesarferreira** [comment]
can you please elaborate?

**Comment by diogo10** [comment]
The project was very small. I just didn't use the libraries.  I think that If I exclude the okhttp library in one of the libraries(AndroidQuickUtils or parse.com) should work,

**Comment by cesarferreira** [comment]
You can exclude libraries from a certain library via `build.gradle` ;)

Sample:

```
compile('ch.qos.logback:logback-classic:1.0.0') {
  exclude group: 'org.slf4j', module: 'slf4j-api' //by both name and group
 }
```
