### ISSUE TITLE
Error initing cache 

### ISSUE THREAD

**Issue by DevHossamHassan** [cesarferreira/AndroidQuickUtils#7]
This error message appears  every time I run my app 
02-28 03:42:01.385 32709-32709/me.branded.hossamhassan.ojreetel5eer E/بوابة النقل: Error initing cache

public class OjreetApp extends Application {

```
@Override
public void onCreate() {
    super.onCreate();
    HossLocaleHelper.onCreate(this);
    QuickUtils.init(this);
    initImageLoader(this);


}
```

**Comment by cesarferreira** [comment]
does the app have permission to write on the sdcard?
